name: Deploy Flask Backend to Docker Swarm

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r hrms-flask/requirements.txt

      - name: Run tests
        run: |
          cd hrms-flask
          pytest

  deploy-backend:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and push backend image
        run: |
          cd hrms-flask
          docker build -t localhost:5000/hrms-flask:latest .
          docker push localhost:5000/hrms-flask:latest

      - name: Deploy backend stack
        run: |
          docker stack deploy -c hrms-flask/docker-compose.yaml hrms_flask_stack
