"""Add Project Module fields

Revision ID: 0673051587a6
Revises: 
Create Date: 2026-02-06 11:28:27.352601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0673051587a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_allocation_history',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('project_allocation', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('project_billing', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_billing', sa.Boolean(), nullable=True),
    sa.Column('employee_role', sa.String(length=50), nullable=True),
    sa.Column('is_trainee', sa.Boolean(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('relevant_skills', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('modified_by', sa.String(length=50), nullable=True),
    sa.Column('modified_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('project_history',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client', sa.String(length=50), nullable=True),
    sa.Column('lead_by', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('modified_by', sa.String(length=50), nullable=True),
    sa.Column('modified_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('history_id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))

    with op.batch_alter_table('project_allocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_billing', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_trainee', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('comments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('relevant_skills', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_allocation', schema=None) as batch_op:
        batch_op.drop_column('relevant_skills')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('comments')
        batch_op.drop_column('is_trainee')
        batch_op.drop_column('is_billing')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('description')

    op.drop_table('project_history')
    op.drop_table('project_allocation_history')
    # ### end Alembic commands ###
