"""empty message

Revision ID: 0ccb6d5e2842
Revises: 
Create Date: 2025-12-31 12:30:38.797222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ccb6d5e2842'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('clientname', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('designation',
    sa.Column('designation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('designation_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('designation_id')
    )
    op.create_table('document',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(length=100), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('employee_relieving_letters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emp_id', sa.String(length=50), nullable=False),
    sa.Column('employee_name', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('letter_type', sa.String(length=50), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('last_working_date', sa.Date(), nullable=False),
    sa.Column('relieving_date', sa.Date(), nullable=False),
    sa.Column('resignation_date', sa.Date(), nullable=False),
    sa.Column('ctc_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('bonus', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('variables', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('pdf_path', sa.String(length=255), nullable=False),
    sa.Column('employee_email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_score_card',
    sa.Column('employee_id', sa.String(length=10), nullable=False),
    sa.Column('score_card_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('employee_shift_details',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('emp_id', sa.String(length=10), nullable=True),
    sa.Column('emp_name', sa.String(length=100), nullable=True),
    sa.Column('shift_start_from_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holiday',
    sa.Column('holiday_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('holiday_name', sa.String(length=255), nullable=False),
    sa.Column('added_by', sa.String(length=255), nullable=False),
    sa.Column('added_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('holiday_id')
    )
    op.create_table('leave_audit2',
    sa.Column('leave_transaction_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=True),
    sa.Column('leave_type_id', sa.Integer(), nullable=True),
    sa.Column('number_of_days', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=True),
    sa.Column('is_carry_forword', sa.Boolean(), nullable=True),
    sa.Column('insert_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('leave_transaction_id')
    )
    op.create_table('leave_management',
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('unpaid_leaves', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('count', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('privilege_leave_count', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('lateral_hire', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('entry_exempt', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('wfh_count', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('sick_leave_count', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('carry_forward_balance', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('leave_opening_transaction_testing',
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('no_of_days', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('added_by', sa.String(length=100), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('is_carry_forworded', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('leave_type_id', 'employee_id')
    )
    op.create_table('leave_transaction',
    sa.Column('leave_tran_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('leave_type', sa.Integer(), nullable=True),
    sa.Column('from_date', sa.DateTime(), nullable=True),
    sa.Column('to_date', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('no_of_days', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('applied_leave_count', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('hand_over_comments', sa.Text(), nullable=True),
    sa.Column('applied_by', sa.String(length=50), nullable=True),
    sa.Column('application_date', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.Column('approved_date', sa.DateTime(), nullable=True),
    sa.Column('approval_comment', sa.String(length=255), nullable=True),
    sa.Column('leave_status', sa.String(length=50), nullable=True),
    sa.Column('attachments', sa.LargeBinary(), nullable=True),
    sa.Column('is_billable', sa.Boolean(), nullable=True),
    sa.Column('have_customer_approval', sa.String(length=50), nullable=True),
    sa.Column('is_customer_approval_required', sa.Boolean(), nullable=True),
    sa.Column('is_communicated_to_team', sa.Boolean(), nullable=True),
    sa.Column('second_approval_comment', sa.String(length=255), nullable=True),
    sa.Column('second_approver_date', sa.DateTime(), nullable=True),
    sa.Column('is_for_second_approval', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('leave_tran_id')
    )
    op.create_table('leave_transaction2',
    sa.Column('leave_tran_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=True),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.Column('leave_type', sa.Integer(), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('hand_over_comments', sa.String(length=255), nullable=True),
    sa.Column('applied_by', sa.String(length=100), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('approval_comment', sa.String(length=255), nullable=True),
    sa.Column('leave_status', sa.String(length=100), nullable=True),
    sa.Column('attachments', sa.LargeBinary(), nullable=True),
    sa.Column('is_billable', sa.Boolean(), nullable=True),
    sa.Column('applied_leave_count', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temp', sa.Integer(), nullable=True),
    sa.Column('have_customer_approval', sa.String(length=50), nullable=True),
    sa.Column('is_handover_responsibilities', sa.String(length=50), nullable=True),
    sa.Column('is_customer_approval_required', sa.String(length=50), nullable=True),
    sa.Column('is_communicated_to_team', sa.String(length=50), nullable=True),
    sa.Column('second_approval_comment', sa.String(length=255), nullable=True),
    sa.Column('second_approver_date', sa.Date(), nullable=True),
    sa.Column('is_for_second_approval', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('leave_tran_id')
    )
    op.create_table('leave_type',
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('leave_type_id')
    )
    op.create_table('leave_type_master',
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('leave_name', sa.String(length=100), nullable=True),
    sa.Column('yearly_allocation', sa.Integer(), nullable=True),
    sa.Column('monthly_allocation', sa.Integer(), nullable=True),
    sa.Column('requires_customer_approval', sa.Boolean(), nullable=True),
    sa.Column('leave_cards_flag', sa.Boolean(), nullable=True),
    sa.Column('quarterly_allocation', sa.Numeric(precision=18, scale=0), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('leave_type_id')
    )
    op.create_table('lob',
    sa.Column('lob_lead', sa.String(length=50), nullable=False),
    sa.Column('lob', sa.String(length=55), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('lob_lead')
    )
    op.create_table('master_role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name', name='uq_role_name')
    )
    op.create_table('master_sub_role',
    sa.Column('sub_role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sub_role_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('sub_role_id')
    )
    op.create_table('otp_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('otp', sa.String(length=10), nullable=False),
    sa.Column('expiry_time', sa.DateTime(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pc_assignments',
    sa.Column('assignment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('pc_name', sa.String(length=50), nullable=False),
    sa.Column('assignment_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('pcs',
    sa.Column('pcid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pc_name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('warranty_till', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pcid')
    )
    op.create_table('peripherals',
    sa.Column('peripheral_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('peripheral_id')
    )
    op.create_table('project_list',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('skill',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('skill_type', sa.String(length=50), nullable=False),
    sa.Column('skill_category', sa.String(length=255), nullable=True),
    sa.Column('is_master_skill', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('skill_id')
    )
    op.create_table('wfh_check_list',
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('from_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('work_categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('comp_off_transaction',
    sa.Column('comp_off_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('leave_tran_id', sa.Integer(), nullable=True),
    sa.Column('comp_off_date', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['leave_tran_id'], ['leave_transaction.leave_tran_id'], ),
    sa.PrimaryKeyConstraint('comp_off_id')
    )
    op.create_table('customer_holiday',
    sa.Column('leave_tran_id', sa.Integer(), nullable=False),
    sa.Column('worked_date', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['leave_tran_id'], ['leave_transaction.leave_tran_id'], ),
    sa.PrimaryKeyConstraint('leave_tran_id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('contact_number', sa.String(length=15), nullable=True),
    sa.Column('emergency_contact_number', sa.String(length=15), nullable=True),
    sa.Column('emergency_contact_person', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('personal_email', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('ctc', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('team_lead_id', sa.String(length=20), nullable=True),
    sa.Column('highest_qualification', sa.String(length=100), nullable=True),
    sa.Column('employment_status', sa.String(length=50), nullable=True),
    sa.Column('sub_role', sa.Integer(), nullable=True),
    sa.Column('lob_lead', sa.String(length=50), nullable=True),
    sa.Column('is_lead', sa.Boolean(), nullable=True),
    sa.Column('qualification_year_month', sa.String(length=10), nullable=True),
    sa.Column('full_stack_ready', sa.Boolean(), nullable=True),
    sa.Column('date_of_resignation', sa.Date(), nullable=True),
    sa.Column('lwd', sa.Date(), nullable=True),
    sa.Column('lwp', sa.Integer(), nullable=True),
    sa.Column('internship_end_date', sa.Date(), nullable=True),
    sa.Column('probation_end_date', sa.Date(), nullable=True),
    sa.Column('privilege_leaves', sa.Integer(), nullable=True),
    sa.Column('sick_leaves', sa.Integer(), nullable=True),
    sa.Column('remaining_leaves', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lob_lead'], ['lob.lob_lead'], ),
    sa.ForeignKeyConstraint(['sub_role'], ['master_sub_role.sub_role_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_employee_id'), ['employee_id'], unique=True)

    op.create_table('maintenance',
    sa.Column('maintenance_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pcid', sa.Integer(), nullable=False),
    sa.Column('issue_description', sa.String(length=500), nullable=True),
    sa.Column('maintenance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pcid'], ['pcs.pcid'], ),
    sa.PrimaryKeyConstraint('maintenance_id')
    )
    op.create_table('working_late',
    sa.Column('leave_tran_id', sa.Integer(), nullable=False),
    sa.Column('from_time', sa.String(length=5), nullable=True),
    sa.Column('to_time', sa.String(length=5), nullable=True),
    sa.Column('reason_for_working_late', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['leave_tran_id'], ['leave_transaction.leave_tran_id'], ),
    sa.PrimaryKeyConstraint('leave_tran_id')
    )
    op.create_table('capability_development_lead',
    sa.Column('capability_development_lead_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('capability_development_lead_id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('compensatory_off',
    sa.Column('comp_off_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=True),
    sa.Column('comp_off_date', sa.Date(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('leave_tran_id', sa.Integer(), nullable=True),
    sa.Column('comp_off_time', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['leave_tran_id'], ['leave_transaction.leave_tran_id'], ),
    sa.PrimaryKeyConstraint('comp_off_id')
    )
    op.create_table('emp_documents',
    sa.Column('doc_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emp_id', sa.String(length=20), nullable=False),
    sa.Column('tenth', sa.LargeBinary(), nullable=True),
    sa.Column('twelve', sa.LargeBinary(), nullable=True),
    sa.Column('pan', sa.LargeBinary(), nullable=True),
    sa.Column('adhar', sa.LargeBinary(), nullable=True),
    sa.Column('grad', sa.LargeBinary(), nullable=True),
    sa.Column('resume', sa.LargeBinary(), nullable=True),
    sa.Column('tenth_verified', sa.Boolean(), nullable=True),
    sa.Column('twelve_verified', sa.Boolean(), nullable=True),
    sa.Column('pan_verified', sa.Boolean(), nullable=True),
    sa.Column('adhar_verified', sa.Boolean(), nullable=True),
    sa.Column('grad_verified', sa.Boolean(), nullable=True),
    sa.Column('resume_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employee.employee_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doc_id'),
    sa.UniqueConstraint('emp_id')
    )
    op.create_table('emp_feedback_data',
    sa.Column('feedback_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emp_id', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('measures', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('added_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('targeted_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('employee_address',
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('address_type', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('address1', sa.String(length=255), nullable=True),
    sa.Column('address2', sa.String(length=255), nullable=True),
    sa.Column('is_same_permanant', sa.Boolean(), nullable=True),
    sa.Column('zip_code', sa.String(length=6), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'address_type')
    )
    op.create_table('employee_allocations',
    sa.Column('allocation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('work_category_id', sa.Integer(), nullable=True),
    sa.Column('allocation', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project_list.project_id'], ),
    sa.ForeignKeyConstraint(['work_category_id'], ['work_categories.category_id'], ),
    sa.PrimaryKeyConstraint('allocation_id')
    )
    op.create_table('employee_credentials',
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('employee_designation',
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('designation_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'designation_id')
    )
    op.create_table('employee_documents',
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('document_link', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'document_id')
    )
    op.create_table('employee_evaluators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emp_id', sa.String(length=20), nullable=False),
    sa.Column('evaluator_id', sa.String(length=20), nullable=False),
    sa.Column('assigned_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['evaluator_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_goal',
    sa.Column('goal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=False),
    sa.Column('set_by_employee_id', sa.String(length=20), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['set_by_employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.skill_id'], ),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.create_table('employee_policy_acknowledgement_status',
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('leave_policy_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('work_from_home_policy_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('exit_policy_and_process_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('salary_advance_recovery_policy_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('probation_to_confirmation_policy_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('salary_and_appraisal_policy_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('warning_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('employee_previous_experience',
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('company_address', sa.String(length=255), nullable=True),
    sa.Column('previous_designation', sa.String(length=100), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'company_name')
    )
    op.create_table('employee_project',
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'project_id')
    )
    op.create_table('employee_role',
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['master_role.role_id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'role_id')
    )
    op.create_table('employee_skill',
    sa.Column('employee_skill_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('skill_level', sa.String(length=50), nullable=True),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('is_ready_date', sa.DateTime(), nullable=True),
    sa.Column('self_evaluation', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_by_lead', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('full_stack_ready', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.skill_id'], ),
    sa.PrimaryKeyConstraint('employee_skill_id'),
    sa.UniqueConstraint('employee_id', 'skill_id', name='uq_employee_skill')
    )
    op.create_table('lateral_and_exempt',
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('shift_start_from_time', sa.String(length=20), nullable=True),
    sa.Column('lateral_hire', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('lead_assigned_by_hr',
    sa.Column('emp_id', sa.String(length=20), nullable=False),
    sa.Column('lead_id', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('emp_id', 'lead_id')
    )
    op.create_table('leave_audit',
    sa.Column('leave_transaction_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=True),
    sa.Column('leave_type_id', sa.Integer(), nullable=True),
    sa.Column('number_of_days', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=True),
    sa.Column('is_carry_forword', sa.Boolean(), nullable=True),
    sa.Column('insert_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('leave_transaction_id')
    )
    op.create_table('leave_opening_transaction',
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('no_of_days', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('added_by', sa.String(length=100), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('is_carry_forworded', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('leave_type_id', 'employee_id')
    )
    op.create_table('project',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('client', sa.String(length=50), nullable=True),
    sa.Column('lead_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_by'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('capability_development_lead_assignment',
    sa.Column('capability_development_lead_assignment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assigned_employee_id', sa.String(length=20), nullable=False),
    sa.Column('capability_development_lead_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_employee_id'], ['employee.employee_id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['capability_development_lead_id'], ['capability_development_lead.capability_development_lead_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('capability_development_lead_assignment_id'),
    sa.UniqueConstraint('assigned_employee_id', 'capability_development_lead_id', name='uq_capability_development_lead_assignment_employee_lead')
    )
    op.create_table('employee_skill_review',
    sa.Column('review_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_id', sa.String(length=20), nullable=False),
    sa.Column('evaluator_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('comments', sa.String(length=500), nullable=True),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('review_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['evaluator_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['skill_id', 'employee_id'], ['employee_skill.skill_id', 'employee_skill.employee_id'], ),
    sa.PrimaryKeyConstraint('review_id'),
    sa.UniqueConstraint('employee_id', 'skill_id', name='uq_employee_skill_evaluator')
    )
    with op.batch_alter_table('employee_skill_review', schema=None) as batch_op:
        batch_op.create_index('ix_employee_skill_review_employee_skill', ['employee_id', 'skill_id'], unique=False)
        batch_op.create_index('ix_employee_skill_review_evaluator', ['evaluator_id'], unique=False)

    op.create_table('project_allocation',
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_allocation', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('project_billing', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('employee_role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_allocation')
    with op.batch_alter_table('employee_skill_review', schema=None) as batch_op:
        batch_op.drop_index('ix_employee_skill_review_evaluator')
        batch_op.drop_index('ix_employee_skill_review_employee_skill')

    op.drop_table('employee_skill_review')
    op.drop_table('capability_development_lead_assignment')
    op.drop_table('project')
    op.drop_table('leave_opening_transaction')
    op.drop_table('leave_audit')
    op.drop_table('lead_assigned_by_hr')
    op.drop_table('lateral_and_exempt')
    op.drop_table('employee_skill')
    op.drop_table('employee_role')
    op.drop_table('employee_project')
    op.drop_table('employee_previous_experience')
    op.drop_table('employee_policy_acknowledgement_status')
    op.drop_table('employee_goal')
    op.drop_table('employee_evaluators')
    op.drop_table('employee_documents')
    op.drop_table('employee_designation')
    op.drop_table('employee_credentials')
    op.drop_table('employee_allocations')
    op.drop_table('employee_address')
    op.drop_table('emp_feedback_data')
    op.drop_table('emp_documents')
    op.drop_table('compensatory_off')
    op.drop_table('capability_development_lead')
    op.drop_table('working_late')
    op.drop_table('maintenance')
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_employee_id'))

    op.drop_table('employee')
    op.drop_table('customer_holiday')
    op.drop_table('comp_off_transaction')
    op.drop_table('work_categories')
    op.drop_table('wfh_check_list')
    op.drop_table('skill')
    op.drop_table('project_list')
    op.drop_table('peripherals')
    op.drop_table('pcs')
    op.drop_table('pc_assignments')
    op.drop_table('otp_requests')
    op.drop_table('master_sub_role')
    op.drop_table('master_role')
    op.drop_table('lob')
    op.drop_table('leave_type_master')
    op.drop_table('leave_type')
    op.drop_table('leave_transaction2')
    op.drop_table('leave_transaction')
    op.drop_table('leave_opening_transaction_testing')
    op.drop_table('leave_management')
    op.drop_table('leave_audit2')
    op.drop_table('holiday')
    op.drop_table('employee_shift_details')
    op.drop_table('employee_score_card')
    op.drop_table('employee_relieving_letters')
    op.drop_table('document')
    op.drop_table('designation')
    op.drop_table('client')
    # ### end Alembic commands ###
