"""empty message

Revision ID: 1851e161f1f0
Revises: 
Create Date: 2026-02-19 15:14:22.709181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1851e161f1f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_skill', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
