"""empty message

Revision ID: 2600a1644c89
Revises: 
Create Date: 2026-02-06 15:12:30.014613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2600a1644c89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hardware_maintenance', schema=None) as batch_op:
        batch_op.alter_column('maintenance_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hardware_maintenance', schema=None) as batch_op:
        batch_op.alter_column('maintenance_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
