"""empty message

Revision ID: 2c258b134f35
Revises: c0c6e428938f
Create Date: 2026-01-01 11:19:08.999642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c258b134f35'
down_revision = 'c0c6e428938f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_customer_approved', sa.Boolean(), server_default=sa.text('false'), nullable=True))
        batch_op.add_column(sa.Column('second_approval_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('second_approval_by', sa.String(length=20), nullable=True))
        batch_op.alter_column('applied_by',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('approved_by',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'employee', ['second_approval_by'], ['employee_id'])
        batch_op.create_foreign_key(None, 'employee', ['applied_by'], ['employee_id'])
        batch_op.create_foreign_key(None, 'employee', ['approved_by'], ['employee_id'])
        batch_op.drop_column('second_approver_date')
        batch_op.drop_column('have_customer_approval')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('have_customer_approval', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('second_approver_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('approved_by',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('applied_by',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('second_approval_by')
        batch_op.drop_column('second_approval_date')
        batch_op.drop_column('is_customer_approved')

    # ### end Alembic commands ###
