"""empty message

Revision ID: 31fa531b10e3
Revises: 57a4b91c6db5
Create Date: 2026-01-02 16:25:06.527758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31fa531b10e3'
down_revision = '57a4b91c6db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approver_id', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'employee', ['approver_id'], ['employee_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('approver_id')

    # ### end Alembic commands ###
