"""empty message

Revision ID: 39af95f10537
Revises: 
Create Date: 2026-02-05 15:56:18.107192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39af95f10537'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emp_documents')
    with op.batch_alter_table('employee_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('emp_id', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('doc_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('blob_name', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('container_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('blob_url', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('file_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('content_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verified_by', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_emp_doc_type', ['emp_id', 'doc_type'])
        batch_op.create_unique_constraint(None, ['blob_name'])
        batch_op.drop_constraint('employee_documents_employee_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'employee', ['emp_id'], ['employee_id'], ondelete='CASCADE')
        batch_op.drop_column('employee_id')
        batch_op.drop_column('document_link')
        batch_op.drop_column('document_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('document_link', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('employee_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('employee_documents_employee_id_fkey', 'employee', ['employee_id'], ['employee_id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('uq_emp_doc_type', type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('uploaded_at')
        batch_op.drop_column('verified_by')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('content_type')
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_name')
        batch_op.drop_column('blob_url')
        batch_op.drop_column('container_name')
        batch_op.drop_column('blob_name')
        batch_op.drop_column('doc_type')
        batch_op.drop_column('emp_id')
        batch_op.drop_column('id')

    op.create_table('emp_documents',
    sa.Column('doc_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('emp_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('tenth', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('twelve', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('pan', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('adhar', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('grad', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('resume', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('tenth_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('twelve_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pan_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('adhar_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('grad_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('resume_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified_by', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employee.employee_id'], name='emp_documents_emp_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doc_id', name='emp_documents_pkey'),
    sa.UniqueConstraint('emp_id', name='emp_documents_emp_id_key')
    )
    # ### end Alembic commands ###
