"""empty message

Revision ID: 40d02607ecfc
Revises: 
Create Date: 2026-02-07 11:15:48.726326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d02607ecfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_frequency', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('report_for', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('report_for')
        batch_op.drop_column('report_frequency')

    # ### end Alembic commands ###
