"""empty message

Revision ID: 5f3ab2e8c3ba
Revises: 
Create Date: 2026-02-04 15:58:17.262456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3ab2e8c3ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_credentials', schema=None) as batch_op:
        batch_op.drop_column('password')

    with op.batch_alter_table('employee_skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_skill', schema=None) as batch_op:
        batch_op.drop_column('skill_category')

    with op.batch_alter_table('employee_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
