"""empty message

Revision ID: 6985fcc5861c
Revises: 
Create Date: 2026-02-18 12:22:12.007177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6985fcc5861c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_goal_enhanced',
    sa.Column('goal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('for_employee_id', sa.String(length=20), nullable=False),
    sa.Column('set_by_employee_id', sa.String(length=20), nullable=False),
    sa.Column('goal_type', sa.String(length=20), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('goal_title', sa.String(length=255), nullable=True),
    sa.Column('goal_description', sa.Text(), nullable=True),
    sa.Column('goal_category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['for_employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['set_by_employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['master_skills.skill_id'], ),
    sa.PrimaryKeyConstraint('goal_id')
    )
    with op.batch_alter_table('employee_goal_enhanced', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_goal_enhanced_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_goal_enhanced_for_employee_id'), ['for_employee_id'], unique=False)
        batch_op.create_index('ix_employee_goal_enhanced_status_deadline', ['for_employee_id', 'status', 'deadline'], unique=False)

    op.create_table('employee_performance_metrics',
    sa.Column('metric_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('skill_proficiency_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('goal_completion_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('peer_feedback_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overall_performance_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('goals_set_count', sa.Integer(), nullable=True),
    sa.Column('goals_completed_count', sa.Integer(), nullable=True),
    sa.Column('skills_evaluated_count', sa.Integer(), nullable=True),
    sa.Column('feedback_received_count', sa.Integer(), nullable=True),
    sa.Column('calculated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('metric_id'),
    sa.UniqueConstraint('employee_id', 'period_type', 'period_start', 'period_end', name='uq_employee_performance_metrics_period')
    )
    with op.batch_alter_table('employee_performance_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_performance_metrics_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index('ix_employee_performance_metrics_period', ['employee_id', 'period_type', 'period_start'], unique=False)

    op.create_table('employee_feedback',
    sa.Column('feedback_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('for_employee_id', sa.String(length=20), nullable=False),
    sa.Column('feedback_by_id', sa.String(length=20), nullable=False),
    sa.Column('feedback_category', sa.String(length=50), nullable=False),
    sa.Column('related_skill_id', sa.Integer(), nullable=True),
    sa.Column('related_goal_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=False),
    sa.Column('is_visible_to_employee', sa.Boolean(), nullable=False),
    sa.Column('feedback_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_by_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['for_employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['related_goal_id'], ['employee_goal_enhanced.goal_id'], ),
    sa.ForeignKeyConstraint(['related_skill_id'], ['master_skills.skill_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    with op.batch_alter_table('employee_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_feedback_feedback_date'), ['feedback_date'], unique=False)
        batch_op.create_index('ix_employee_feedback_for_date', ['for_employee_id', 'feedback_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_feedback_for_employee_id'), ['for_employee_id'], unique=False)

    op.create_table('goal_comment',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('commented_by_id', sa.String(length=20), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('comment_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commented_by_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['employee_goal_enhanced.goal_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    with op.batch_alter_table('goal_comment', schema=None) as batch_op:
        batch_op.create_index('ix_goal_comment_goal_date', ['goal_id', 'comment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_comment_goal_id'), ['goal_id'], unique=False)

    op.create_table('goal_review',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by_id', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('review_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['employee_goal_enhanced.goal_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    with op.batch_alter_table('goal_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_review_goal_id'), ['goal_id'], unique=False)

    op.create_table('skill_progress_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_skill_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('previous_level', sa.String(length=50), nullable=True),
    sa.Column('new_level', sa.String(length=50), nullable=True),
    sa.Column('previous_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('new_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('updated_by_id', sa.String(length=20), nullable=False),
    sa.Column('update_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['employee_skill_id'], ['employee_skill.employee_skill_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['master_skills.skill_id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('skill_progress_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_progress_log_employee_skill_id'), ['employee_skill_id'], unique=False)
        batch_op.create_index('ix_skill_progress_log_skill_date', ['employee_skill_id', 'update_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_progress_log_update_date'), ['update_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_progress_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_progress_log_update_date'))
        batch_op.drop_index('ix_skill_progress_log_skill_date')
        batch_op.drop_index(batch_op.f('ix_skill_progress_log_employee_skill_id'))

    op.drop_table('skill_progress_log')
    with op.batch_alter_table('goal_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_review_goal_id'))

    op.drop_table('goal_review')
    with op.batch_alter_table('goal_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_comment_goal_id'))
        batch_op.drop_index('ix_goal_comment_goal_date')

    op.drop_table('goal_comment')
    with op.batch_alter_table('employee_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_feedback_for_employee_id'))
        batch_op.drop_index('ix_employee_feedback_for_date')
        batch_op.drop_index(batch_op.f('ix_employee_feedback_feedback_date'))

    op.drop_table('employee_feedback')
    with op.batch_alter_table('employee_performance_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_employee_performance_metrics_period')
        batch_op.drop_index(batch_op.f('ix_employee_performance_metrics_employee_id'))

    op.drop_table('employee_performance_metrics')
    with op.batch_alter_table('employee_goal_enhanced', schema=None) as batch_op:
        batch_op.drop_index('ix_employee_goal_enhanced_status_deadline')
        batch_op.drop_index(batch_op.f('ix_employee_goal_enhanced_for_employee_id'))
        batch_op.drop_index(batch_op.f('ix_employee_goal_enhanced_deadline'))

    op.drop_table('employee_goal_enhanced')
    # ### end Alembic commands ###
