"""empty message

Revision ID: 8b18a58342db
Revises: 
Create Date: 2026-02-20 15:33:29.879439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b18a58342db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_capability_group',
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('employee_capability_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.String(length=20), nullable=False),
    sa.Column('assigned_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['master_capability_group.group_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_capability_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_capability_group_employee_id'), ['employee_id'], unique=True)

    op.create_table('employee_capability_group_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.String(length=20), nullable=False),
    sa.Column('assigned_on', sa.DateTime(), nullable=False),
    sa.Column('removed_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['master_capability_group.group_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_capability_group_history', schema=None) as batch_op:
        batch_op.create_index('ix_emp_cap_group_history_emp_date', ['employee_id', 'removed_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_capability_group_history_employee_id'), ['employee_id'], unique=False)

    op.create_table('employee_goal',
    sa.Column('goal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('for_employee_id', sa.String(length=20), nullable=False),
    sa.Column('set_by_employee_id', sa.String(length=20), nullable=False),
    sa.Column('goal_type', sa.String(length=20), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('goal_title', sa.String(length=255), nullable=True),
    sa.Column('goal_description', sa.Text(), nullable=True),
    sa.Column('goal_category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['for_employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['set_by_employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['master_skills.skill_id'], ),
    sa.PrimaryKeyConstraint('goal_id')
    )
    with op.batch_alter_table('employee_goal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_goal_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_goal_for_employee_id'), ['for_employee_id'], unique=False)
        batch_op.create_index('ix_employee_goal_status_deadline', ['for_employee_id', 'status', 'deadline'], unique=False)

    op.create_table('employee_review',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('reviewed_date', sa.Date(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('other_comments', sa.Text(), nullable=True),
    sa.Column('file_link', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    with op.batch_alter_table('employee_review', schema=None) as batch_op:
        batch_op.create_index('ix_employee_review_date', ['employee_id', 'review_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_review_employee_id'), ['employee_id'], unique=False)

    op.create_table('employee_feedback',
    sa.Column('feedback_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('for_employee_id', sa.String(length=20), nullable=False),
    sa.Column('feedback_by_id', sa.String(length=20), nullable=False),
    sa.Column('feedback_category', sa.String(length=50), nullable=False),
    sa.Column('related_skill_id', sa.Integer(), nullable=True),
    sa.Column('related_goal_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=False),
    sa.Column('is_visible_to_employee', sa.Boolean(), nullable=False),
    sa.Column('feedback_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_by_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['for_employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['related_goal_id'], ['employee_goal.goal_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_skill_id'], ['master_skills.skill_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    with op.batch_alter_table('employee_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_feedback_feedback_date'), ['feedback_date'], unique=False)
        batch_op.create_index('ix_employee_feedback_for_date', ['for_employee_id', 'feedback_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_feedback_for_employee_id'), ['for_employee_id'], unique=False)

    op.create_table('employee_goal_comment',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('commented_by_id', sa.String(length=20), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('comment_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commented_by_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['employee_goal.goal_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    with op.batch_alter_table('employee_goal_comment', schema=None) as batch_op:
        batch_op.create_index('ix_employee_goal_comment_goal_date', ['goal_id', 'comment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_goal_comment_goal_id'), ['goal_id'], unique=False)

    op.create_table('employee_goal_review',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by_id', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('review_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['employee_goal.goal_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    with op.batch_alter_table('employee_goal_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_goal_review_goal_id'), ['goal_id'], unique=False)

    with op.batch_alter_table('employee_skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_skill', schema=None) as batch_op:
        batch_op.drop_column('notes')

    with op.batch_alter_table('employee_goal_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_goal_review_goal_id'))

    op.drop_table('employee_goal_review')
    with op.batch_alter_table('employee_goal_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_goal_comment_goal_id'))
        batch_op.drop_index('ix_employee_goal_comment_goal_date')

    op.drop_table('employee_goal_comment')
    with op.batch_alter_table('employee_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_feedback_for_employee_id'))
        batch_op.drop_index('ix_employee_feedback_for_date')
        batch_op.drop_index(batch_op.f('ix_employee_feedback_feedback_date'))

    op.drop_table('employee_feedback')
    with op.batch_alter_table('employee_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_review_employee_id'))
        batch_op.drop_index('ix_employee_review_date')

    op.drop_table('employee_review')
    with op.batch_alter_table('employee_goal', schema=None) as batch_op:
        batch_op.drop_index('ix_employee_goal_status_deadline')
        batch_op.drop_index(batch_op.f('ix_employee_goal_for_employee_id'))
        batch_op.drop_index(batch_op.f('ix_employee_goal_deadline'))

    op.drop_table('employee_goal')
    with op.batch_alter_table('employee_capability_group_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_capability_group_history_employee_id'))
        batch_op.drop_index('ix_emp_cap_group_history_emp_date')

    op.drop_table('employee_capability_group_history')
    with op.batch_alter_table('employee_capability_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_capability_group_employee_id'))

    op.drop_table('employee_capability_group')
    op.drop_table('master_capability_group')
    # ### end Alembic commands ###
