"""empty message

Revision ID: 91091152ef62
Revises: 
Create Date: 2026-02-20 12:12:30.134887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91091152ef62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_review',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('reviewed_date', sa.Date(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('other_comments', sa.Text(), nullable=True),
    sa.Column('file_link', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    with op.batch_alter_table('employee_review', schema=None) as batch_op:
        batch_op.create_index('ix_employee_review_date', ['employee_id', 'review_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_review_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_review_employee_id'))
        batch_op.drop_index('ix_employee_review_date')

    op.drop_table('employee_review')
    # ### end Alembic commands ###
