"""empty message

Revision ID: 9ec69a753fe7
Revises: 121edd9acae8
Create Date: 2025-12-31 10:34:37.816787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec69a753fe7'
down_revision = '121edd9acae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=False))

    with op.batch_alter_table('otp_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempt_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp_requests', schema=None) as batch_op:
        batch_op.drop_column('attempt_count')

    with op.batch_alter_table('employee_credentials', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
