"""empty message

Revision ID: d2e77ae9fbd5
Revises: 
Create Date: 2026-02-20 14:49:51.223865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e77ae9fbd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_capability_group',
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('employee_capability_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.String(length=20), nullable=False),
    sa.Column('assigned_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['master_capability_group.group_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_capability_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_capability_group_employee_id'), ['employee_id'], unique=True)

    op.create_table('employee_capability_group_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.String(length=20), nullable=False),
    sa.Column('assigned_on', sa.DateTime(), nullable=False),
    sa.Column('removed_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['master_capability_group.group_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_capability_group_history', schema=None) as batch_op:
        batch_op.create_index('ix_emp_cap_group_history_emp_date', ['employee_id', 'removed_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_capability_group_history_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_capability_group_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_capability_group_history_employee_id'))
        batch_op.drop_index('ix_emp_cap_group_history_emp_date')

    op.drop_table('employee_capability_group_history')
    with op.batch_alter_table('employee_capability_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_capability_group_employee_id'))

    op.drop_table('employee_capability_group')
    op.drop_table('master_capability_group')
    # ### end Alembic commands ###
