"""empty message

Revision ID: e00c5eda2c16
Revises: 
Create Date: 2026-02-25 12:25:41.939855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e00c5eda2c16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_opening_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_opening_transaction', schema=None) as batch_op:
        batch_op.drop_column('comments')

    # ### end Alembic commands ###
