"""empty message

Revision ID: e73b6e1e7cb3
Revises: 
Create Date: 2026-02-23 13:02:40.191198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73b6e1e7cb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_configuration',
    sa.Column('email_config_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('email_frequency', sa.String(length=50), nullable=False),
    sa.Column('email_time', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email_config_id')
    )
    with op.batch_alter_table('email_configuration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_configuration_config_key'), ['config_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_configuration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_configuration_config_key'))

    op.drop_table('email_configuration')
    # ### end Alembic commands ###
