"""empty message

Revision ID: e777a29403b8
Revises: 
Create Date: 2026-02-18 17:49:04.942895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e777a29403b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_transaction', schema=None) as batch_op:
        batch_op.alter_column('no_of_days',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_transaction', schema=None) as batch_op:
        batch_op.alter_column('no_of_days',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
