"""Add project_status field

Revision ID: ebbf7ec67563
Revises: 0673051587a6
Create Date: 2026-02-06 12:07:25.487701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebbf7ec67563'
down_revision = '0673051587a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_status', sa.String(length=50), nullable=False, server_default='Active'))

    with op.batch_alter_table('project_allocation', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('project_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_history', schema=None) as batch_op:
        batch_op.drop_column('project_status')

    with op.batch_alter_table('project_allocation', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('project_status')

    # ### end Alembic commands ###
