"""empty message

Revision ID: ec3b666f035f
Revises: c3c7e8a43392
Create Date: 2026-02-04 00:44:30.880195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec3b666f035f'
down_revision = 'c3c7e8a43392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_credentials', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
